-- MySQL Script generated by MySQL Workbench
-- 12/18/14 12:17:38
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jcincms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jcincms` DEFAULT CHARACTER SET utf8 ;
USE `jcincms` ;

-- -----------------------------------------------------
-- Table `jcincms`.`tb_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_menu` (
  `id` VARCHAR(120) NOT NULL,
  `name` VARCHAR(120) NULL DEFAULT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `path` VARCHAR(120) NULL DEFAULT NULL,
  `parentId` VARCHAR(120) NULL,
  `createDate` DATE NULL,
  `icon` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_menu1` (`parentId` ASC),
  CONSTRAINT `fk_menu_menu1`
    FOREIGN KEY (`parentId`)
    REFERENCES `jcincms`.`tb_menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_role` (
  `id` VARCHAR(120) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `createDate` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_role_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_role_menu` (
  `role_id` VARCHAR(120) NULL,
  `menu_id` VARCHAR(120) NULL,
  `id` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_role1` (`role_id` ASC),
  INDEX `fk_table1_menu1` (`menu_id` ASC),
  INDEX `fk_role_menu_menu1` (`menu_id` ASC),
  INDEX `fk_role_menu_role1` (`role_id` ASC),
  CONSTRAINT `fk_role_menu_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `jcincms`.`tb_menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_menu_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `jcincms`.`tb_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_category` (
  `id` VARCHAR(120) NOT NULL,
  `name` VARCHAR(120) NULL DEFAULT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `parentId` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_article` (
  `id` VARCHAR(120) NOT NULL,
  `title` VARCHAR(120) NULL DEFAULT NULL,
  `author` VARCHAR(120) NULL DEFAULT NULL,
  `content` VARCHAR(10000) NULL DEFAULT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `tb_category_id` VARCHAR(120) NULL DEFAULT NULL,
  `createDate` DATE NULL DEFAULT NULL,
  `source` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_id` (`tb_category_id` ASC),
  CONSTRAINT `fk_category_id`
    FOREIGN KEY (`tb_category_id`)
    REFERENCES `jcincms`.`tb_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_asset` (
  `id` VARCHAR(120) NOT NULL,
  `name` VARCHAR(120) NULL DEFAULT NULL,
  `path` VARCHAR(4500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_comment` (
  `id` VARCHAR(120) NOT NULL,
  `content` VARCHAR(10000) NULL DEFAULT NULL,
  `tb_article_id` VARCHAR(120) NULL DEFAULT NULL,
  `parentId` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbartilce` (`tb_article_id` ASC),
  INDEX `fk_tb_comment_tb_comment1` (`parentId` ASC),
  CONSTRAINT `fk_tbartilce`
    FOREIGN KEY (`tb_article_id`)
    REFERENCES `jcincms`.`tb_article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_comment_tb_comment1`
    FOREIGN KEY (`parentId`)
    REFERENCES `jcincms`.`tb_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_user` (
  `id` VARCHAR(120) NOT NULL,
  `username` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(120) NULL DEFAULT NULL,
  `status` SMALLINT(6) NULL DEFAULT '1',
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `enabled` TINYINT(1) NULL,
  `createDate` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = gb2312;


-- -----------------------------------------------------
-- Table `jcincms`.`tb_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jcincms`.`tb_user_role` (
  `id` VARCHAR(120) NOT NULL,
  `user_id` VARCHAR(120) NOT NULL,
  `role_id` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_user` (`user_id` ASC),
  INDEX `fk_user_role_role1` (`role_id` ASC),
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `jcincms`.`tb_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `jcincms`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = gb2312;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
